Downloading Keremberke yolo8m

In [ ]:
#!pip install git+https://github.com/ultralytics/ultralytics.git@main

#!git lfs install must be installed first

In [2]:
#downloading keremberk models

!git clone https://huggingface.co/keremberke/yolov8m-table-extraction

fatal: destination path 'yolov8m-table-extraction' already exists and is not an empty directory.


Fine tuning keremberke8M

In [26]:
from datetime import datetime

datetime.now()

datetime.datetime(2023, 12, 19, 14, 13, 13, 898914)

In [1]:
#training
!yolo task=detect mode=train model=/home/suparna/PycharmProjects/YOLO_finetuning_dec/yolov8m-table-extraction/best.pt imgsz=640 data=/home/suparna/PycharmProjects/YOLO_finetuning_dec/FT_data.yaml epochs=18 batch=10 name=bor_unBor_ft
#/home/suparna/PycharmProjects/TableDetection/YOLO_FT_tables/runs/detect/keremberke8m_106/weights/best.pt this model was trained for 10 epoch, taking the best from the 10 epochs and finetuning further for 40 epochs

/home/suparna/anaconda3/envs/idp_0/lib/python3.8/site-packages/torch/cuda/__init__.py:138: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 11040). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
Ultralytics YOLOv8.0.43 🚀 Python-3.8.18 torch-2.1.1+cu121 CPU
yolo/engine/trainer: task=detect, mode=train, model=/home/suparna/PycharmProjects/FinetuningYOLOv8_Table/runs/detect/ft_roundII_upto50epochs/weights/best.pt, data=FT_data.yaml, epochs=18, patience=50, batch=10, imgsz=640, save=True, save_period=-1, cache=False, device=None, workers=0, project=None, name=ft_roundII_32to50epochs, exist_ok=False, pretrained=False, optimizer=SGD,

In [4]:
#validation
!yolo task=detect mode=val model=/home/suparna/PycharmProjects/YOLO_finetuning_dec/runs/detect/beauty_yolo_ft2/weights/best.pt name=epoch100_eval data=FT_data.yaml imgsz=640


/home/suparna/anaconda3/envs/idp_0/lib/python3.8/site-packages/torch/cuda/__init__.py:138: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 11040). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
Ultralytics YOLOv8.0.230 🚀 Python-3.8.18 torch-2.1.1+cu121 CPU (Intel Core(TM) i5-7200U 2.50GHz)
Model summary (fused): 218 layers, 25840339 parameters, 0 gradients, 78.7 GFLOPs
val: Scanning /home/suparna/PycharmProjects/YOLO_finetuning_dec/data/val/labels.
val: New cache created: /home/suparna/PycharmProjects/YOLO_finetuning_dec/data/val/labels.cache
                 Class     Images  Instances      Box(P          R      mAP50  m
    

1. Predicting on test data1. 

In [6]:
!yolo task=detect mode=predict model=/home/suparna/PycharmProjects/YOLO_finetuning_dec/runs/detect/beauty_yolo_ft2/weights/best.pt imgsz=640 conf=0.25 iou=.45 agnostic_nms=False source=/home/suparna/PycharmProjects/YOLO_finetuning_dec/data/test/images save=True name=testpostgpu_100epochs

/home/suparna/anaconda3/envs/idp_0/lib/python3.8/site-packages/torch/cuda/__init__.py:138: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 11040). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
Ultralytics YOLOv8.0.230 🚀 Python-3.8.18 torch-2.1.1+cu121 CPU (Intel Core(TM) i5-7200U 2.50GHz)
Model summary (fused): 218 layers, 25840339 parameters, 0 gradients, 78.7 GFLOPs

image 1/39 /home/suparna/PycharmProjects/YOLO_finetuning_dec/data/test/images/B_A_8.png: 640x480 1 Table, 668.6ms
image 2/39 /home/suparna/PycharmProjects/YOLO_finetuning_dec/data/test/images/B_B_33.png: 640x416 1 Table, 530.4ms
image 3/39 /home/suparna/Pycharm

Prediction on Vericred pdf images.02-01-24

In [7]:
!yolo task=detect mode=predict model=/home/suparna/PycharmProjects/YOLO_finetuning_dec/runs/detect/beauty_yolo_ft2/weights/best.pt imgsz=640 conf=0.25 iou=.45 agnostic_nms=False source=/home/suparna/PycharmProjects/TableExtraction/data/cropped_tables save=True name=testpostgpu_100epochs

/home/suparna/anaconda3/envs/idp_0/lib/python3.8/site-packages/torch/cuda/__init__.py:138: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 11040). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
Ultralytics YOLOv8.0.230 🚀 Python-3.8.18 torch-2.1.1+cu121 CPU (Intel Core(TM) i5-7200U 2.50GHz)
Model summary (fused): 218 layers, 25840339 parameters, 0 gradients, 78.7 GFLOPs

image 1/82 /home/suparna/PycharmProjects/TableExtraction/data/cropped_tables/Vericred3sni_0_1.png: 448x640 1 Table, 1325.9ms
image 2/82 /home/suparna/PycharmProjects/TableExtraction/data/cropped_tables/Vericred3sni_0_1_1.png: 448x640 1 Table, 1461.3ms
image 3/8

In [ ]:
from ultralytics import YOLO
from PIL import Image,ImageOps
import os

# load model
model = YOLO('/home/suparna/PycharmProjects/TableDetection/YOLO_FT_tables/best_model/keremberke8m_10_50/weights/best.pt')

# set model parameters
model.overrides['conf'] = 0.25  # NMS confidence threshold
model.overrides['iou'] = 0.45  # NMS IoU threshold
model.overrides['agnostic_nms'] = False  # NMS class-agnostic
model.overrides['max_det'] = 1000  # maximum number of detections per image

def detect_crop_save_tables(image):
    print(image)
    # set image
    #image = "/home/suparna/PycharmProjects/TableDetection/all_Data/FinQA_tables/combined_tables-056.png"

    # perform inference
    results = model.predict("/home/suparna/PycharmProjects/TableDetection/all_Data/FinQA_tables/"+image)
    print(results)
    # observe results
    print(results[0].boxes)
    # render = render_result(model=model, image=image, result=results[0])
    # render.show()
    file_name="enersys"+image[-6:]
    image_path=f'/home/suparna/PycharmProjects/TableDetection/all_Data/FinQA_tables'       
        
    #render=render.save(f'{image_path}/{file_name}' )
    print(results[0].boxes.xyxy)
    print(results[0].boxes.xyxyn)
    print(results[0].boxes.xywh)
    print(results[0].boxes.xywhn)

    all_boxes=results[0].boxes.data.cpu().numpy()
    for i, box in enumerate(all_boxes):
        im2 = Image.open(image)
        input_image = ImageOps.grayscale(im2) 

        x1, y1, x2, y2, conf, cls = box
        tables = im2.crop((x1-10, y1-10, x2+10, y2+10))
        
        plate_filename = f'/home/suparna/PycharmProjects/TableDetection/Approaches_results/enersys_cropped_tables/{image[-7:]}_cropped_margin10_{i+1}_.png'
        tables.save(plate_filename)


images=os.listdir("/home/suparna/PycharmProjects/TableDetection/all_Data/FinQA_tables")
for img in images:
    print(img)
    detect_crop_save_tables(img)

In [8]:
from ultralytics import YOLO
from PIL import Image, ImageOps
import os
# from image_processing.remove_horizontal_lines import remove_h_line
# from image_processing.dialate_vertical_space import add_v_space
# from image_processing.dialate_horizontal_space import add_h_space

model_path="/home/suparna/PycharmProjects/TableExtraction/model/beauty_yolo_ft3_150/weights/best.pt"
markedtable_path="/home/suparna/PycharmProjects/TableExtraction/data/tables_marked/"
cropped_image_path="/home/suparna/PycharmProjects/TableExtraction/data/cropped_tables/"
coords_txt_path="/home/suparna/PycharmProjects/TableExtraction/data/coordinates/"
# load model
#model = YOLO('yolov8n.pt')  # load an official model
model = YOLO(model_path)

# set model parameters
model.overrides['conf'] = 0.25  # NMS confidence threshold
model.overrides['iou'] = 0.45  # NMS IoU threshold
model.overrides['agnostic_nms'] = False  # NMS class-agnostic
model.overrides['max_det'] = 1000  # maximum number of detections per image


def detect_table(img:str)-> None:
    '''
    Args:
        img: Complete page image
    Returns:None
    steps:
    1. detects the table/tables present in the image
    2. saves the coordinates in coords_txt_path in .txt file with the same as that of the img.
    3. also invokes crop table to crop the image and save in cropped_image_path
    '''

    # 1. detects the table/tables present in the image
    image=img
    file_name = image.split('/')[-1]

    results = model.predict(image)
    #render = render_result(model=model, image=image, result=results[0])
    #render.show()

    #2. saves the coordinates in coords_txt_path in .txt file with the same as that of the img.
    file_name = image.split('/')[-1]
    #render = render.save(f'{markedtable_path}{file_name}')
    #render.show()
    print("boxes")
    print(results[0].boxes.xyxy)
    print(results[0].boxes.xyxyn)
    print(results[0].boxes.xywh)
    print(results[0].boxes.xywhn)

    #3. also invokes crop table to crop the image and save in cropped_image_path
    crop_table(results,image)


def crop_table(results,image:str) -> None:
    '''    
    Args:
        results:list of tensors as detected by the prediction model
        image: path to image

    Returns:None

    '''
    all_boxes = results[0].boxes.data.cpu().numpy()
    print("all boxes")
    print(all_boxes)
    box_coord=[]
    for i, box in enumerate(all_boxes):
        im2 = Image.open(image)
        input_image = ImageOps.grayscale(im2)

        #cropping the tables with an added margin of 20 pixels
        x1, y1, x2, y2, conf, cls = box
        tables = input_image.crop((x1 - 20, y1 - 20, x2 +20, y2 +20))

        table_filename = (f'{cropped_image_path}{image.split("/")[-1][:-4]}_{i + 1}.png')
        box_coord.append([int(x1),int(y1),int(x2),int(y2)])

        tables.save(table_filename)
        #print(box_coord)

    coordsfname=f"{coords_txt_path}{image.split('/')[-1][:-4]}.txt"
    with open(coordsfname, 'w') as f:
        c=str(box_coord)
        f.write(c)


if __name__=="__main__":

    img="data/test/images/B_A_8.png" #only image name
    detect_table(img)



image 1/1 /home/suparna/PycharmProjects/YOLO_finetuning_dec/data/test/images/B_A_8.png: 640x480 1 Table, 582.6ms
Speed: 3.7ms preprocess, 582.6ms inference, 0.9ms postprocess per image at shape (1, 3, 640, 480)
boxes
tensor([[ 40.7488, 115.6442, 548.7826, 750.3737]])
tensor([[0.0684, 0.1373, 0.9208, 0.8912]])
tensor([[294.7657, 433.0089, 508.0338, 634.7295]])
tensor([[0.4946, 0.5143, 0.8524, 0.7538]])
all boxes
[[     40.749      115.64      548.78      750.37     0.98284           0]]
